### ISSUE TITLE
Error creating files: Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by alamenai** [BelkacemYerfa/shadcn-extension#101]
Hi guys,

I tried to install the breadcrumb component using the CLI however I found this error:

![image](https://github.com/user-attachments/assets/32706d37-c230-4a2e-a1a0-c7b01df6f3d8)

I expect the CLI should check if the folder exists first before adding the component otherwise it will be created then add the component's file.

**Comment by BelkacemYerfa** [comment]
Hi @alamenai!

Thanks for your feedback, regardless of the issue, what I assume is that you run the installation command directly before the init command, if that the case, just run the init command after that you can add the component of your choice.

**Comment by alamenai** [comment]
HI @BelkacemYerfa ,

Yes, I directly run the command without running the init as I only need that component.
