### ISSUE TITLE
SmartDateTimeInput with locale frCA minutes are ignored

### ISSUE THREAD

**Issue by j-fdion** [BelkacemYerfa/shadcn-extension#109]
When using frCA instead of fr for locale the minutes are dropped from the parsed date.

20 nov. 2024, 05 h 17 becomes 20 nov. 2024, 05 h 00

When comparing both locale the only difference I see is the way the time is displayed:

fr: 20 nov. 2024, 15:17
frCA: 20 nov. 2024, 05 h 17

Perhaps the " h " section is wrongly parsed?

**Comment by BelkacemYerfa** [comment]
Hello @j-fdion.

Thanks for your feedback, am gonna check the issue later on and try to provide the fix, but if the issue is a parsing issue, it should be related to the chrono node issue, since we're using the default parser they provide, we didn't make our own.

**Comment by j-fdion** [comment]
I tested many ways of writing december.
![image](https://github.com/user-attachments/assets/31f3c294-620d-4fa7-a955-6264a5b241d3)

Seems it comes from chrono nodo indeed. I can alleviate the issue by using the "long" format for months instead of "short" by modifying the formatDateTime function:

`
export const formatDateTime = (
  datetime: Date | string,
  locale: Locale,
  hour12: boolean,
) =>
  new Date(datetime).toLocaleTimeString(locale.code, {
    month: "long", //instead of short
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "numeric",
    hour12,
  });
`
This will work for me :)

**Comment by j-fdion** [comment]
Yes I found a related issue in chrono-node and mentionned the repo owner, I'll see what they can do. Thank you!
