### ISSUE TITLE
How to use your project?

### ISSUE THREAD

**Issue by nicoputzehl** [BelkacemYerfa/shadcn-extension#13]
Hi Belkacem,

I would like to use your project, especially the multiselect component.

However, I don't quite understand how I can use the components.

Your instructions say:
To install Shadcn-extension-component, you need to configure the shadcn/ui component that it uses. You can do this by following the instructions in the Shadcn-ui documentation.

But I can't find the corresponding point in the Shadcn-ui documentation.
Can you help me with this in any way?

Many thanks in advance.

Best regards,

Nico

**Comment by BelkacemYerfa** [comment]
Hi there, @nicoputzehl.

To use the multi-select component from my project, you need to have the shadcn/ui installed in your project. Follow the installation guide in the shadcn/ui documentation: https://ui.shadcn.com/docs/installation

After installing shadcn/ui, you can proceed to the specific component you want to use (e.g., multi-select) component, follow the instructions provided there to install and set up the necessary files.
![image](https://github.com/BelkacemYerfa/shadcn-extension/assets/106016365/645fcc68-910c-4f26-9115-c129ffab0b82)

then create a folder in same directory as your directory that holds your shadcn component , e.g
![image](https://github.com/BelkacemYerfa/shadcn-extension/assets/106016365/2a649ffe-77f1-43e1-805f-9140f4c1b2ab)

Note : the folder you can name it whatever (for me , i name it extension) 

then paste the code from the multi-select-api that you will find , here : 
https://github.com/BelkacemYerfa/shadcn-extension/blob/master/packages/src/components/extension/fancy-multi-select

Now you are ready to use it. Same goes for all of the rest components

Please let me know if you need any further assistance or have additional questions.

**Comment by nicoputzehl** [comment]
Many thanks for the quick reply.

It works now. In principle, all dependencies of the component code must be present in order to use your components.
