### ISSUE TITLE
Hover Issue, on breadcrumbs example in docs

### ISSUE THREAD

**Issue by gaurangrshah** [BelkacemYerfa/shadcn-extension#28]
Currently when you hover over the breadcrumbs on the first one displays a pointer, the rest show a text cursor instead. 

![Kapture 2024-04-03 at 09 50 32](https://github.com/BelkacemYerfa/shadcn-extension/assets/1086269/a21ce7e0-5719-4552-95fb-82fcb2ca6265)

I assume each of them should be links, so it would make sense that each of them also showed the proper cursor on hover.

**Comment by BelkacemYerfa** [comment]
Hello @gaurangrshah .
Thanks for addressing this issue , for your idea about making each one of them a link , could be nice to make a more coherent ui , the cause i have left them like that is to show that the breadcrumb component can be used as you want whatever a link component or a regular item , that can be clicked and the state will be pushed to the url.
But I think it would done matter a lot in this case .

Would love to here your thoughts on that .
Best , Belkacem.

**Comment by gaurangrshah** [comment]
I agree with a cleaner interface I did fork the repo to try and contribute, but I was short on time and noticed that you were purposefully not rendering a link in the other two. My suggestion would be to use the same paradigm as shadcn currently uses and make this a slot component allowing custom implementation using the asChild prop. 

Would be more than happy to contribute, although it takes me awhile to acclimated to new codebases - so I may have a few questions to start. 

On a sidenote, I am currently working on a few components that are built on top of Shadcn myself and would like to of course learn from your efforts as well.

**Comment by BelkacemYerfa** [comment]
Thanks again @gaurangrshah, for your suggestions.
I will look for your suggestion as soon as possible , meanwhile feel free to check the codebase, it would be nice 
if we have you as a contributor.
And about any issues that you have or any sort of questions , just ask i will be more than happy to help you start out.

**Comment by gaurangrshah** [comment]
> Also it would be nice if the component that you are working on, share the same vision as shadcn extension, cause
> it would be very cool to have them , so that the collection will be extended more.

I'd love to contribute not sure if this is the type of component you'd want in this library tho. I may actually turn this into a freemium product would love to discuss more I tried to DM you on twitter but the twitter (x) link you have on the landing page navbar goes to an account that doesn't exist. [Feel free to reach out to me on twitter/x](https://twitter.com/soham_asmi). 

I'd be happy to share the current state of the project with you would love to get your thoughts on that.

**Comment by BelkacemYerfa** [comment]
Ah sorry for that issue , it was my old username , that i have changed.

Feel free to reach me out if you want , this is the correct [link](https://twitter.com/BylkaYf).

**Comment by gaurangrshah** [comment]
Implemented the fix simply by using the nextjs [Link](https://nextjs.org/docs/app/api-reference/components/link) as children to each of the breadcrumb children. As the first link ("Home") in each breadcrumb example already had a Link component as a child, I implemented the same thing for each fo the additional links (Support and Account) in each of the following examples where they were missing:

```shell
        modified:   src/registry/default/example/breadcrumb-demo.tsx
        modified:   src/registry/default/example/breadcrumb/breadcrumb-popover.tsx
        modified:   src/registry/default/example/breadcrumb/breadcrumb-separator.tsx
        modified:   src/registry/default/example/breadcrumb/breadcrumb-variants.tsx
```

I also capitalized the `V` in the heading for "Breadcrumb Variants". this affected the doc file at:
```shell
modified:   content/docs/breadcrumb.mdx
```
