### ISSUE TITLE
File upload component has responsiveness problems

### ISSUE THREAD

**Issue by aymendn** [BelkacemYerfa/shadcn-extension#48]
Hi!

When using a long name with the file upload component in the [docs page](https://shadcn-extension.vercel.app/docs/file-upload), It will overflow like shown in the following image:

![image](https://uploads.linear.app/533d7c4d-b17f-4b6f-b63b-d5e36440f740/903eaeea-700f-466a-bec6-33eeb64d0ce0/b127bfb8-92a9-4752-89d0-57a3ce09d52c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzM2Q3YzRkLWIxN2YtNGI2Zi1iNjNiLWQ1ZTM2NDQwZjc0MC85MDNlYWVlYS03MDBmLTQ2NmEtYmVjNi0zM2VlYjY0ZDBjZTAvYjEyN2JmYjgtOTJhOS00NzUyLTg5ZDAtNTdhM2NlMDlkNTJjIiwiaWF0IjoxNzE0MzY2Mjg0LCJleHAiOjMzMjg0OTI2Mjg0fQ.KZ0MCjcS62_SwglmgVlk9aFf733DjvpIjnC9mYI0gb0)

**Comment by gaurangrshah** [comment]
Thanks for bringing this to our attention. 

@BelkacemYerfa what do u think? Is this something that we can simply truncate the middle of the filename? This way we can show the extension which (correct me if I am wrong) is the most important part. 

i.e.,
```
"502f53af474373...ffff.png"
```

If so we need to see what the max char length is that we want to allow.

**Comment by BelkacemYerfa** [comment]
Actually I agree with @gaurangrshah on that side , in every file upload component the most important thing is the extension of the uploaded file.

We can land a fix for this one in the next release.

Thanks @aymendn for addressing this issue.

**Comment by YusufcanY** [comment]
any updates?
