### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lenocin** [BelkacemYerfa/shadcn-extension#49]
Just FYI, I had to make this change in `command.tsx` to get your multi select to function

```
    ref={ref}
    className={cn(
      "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-[selected='true']:bg-accent aria-[selected='true']:text-accent-foreground data-[disabled='true']:pointer-events-none data-[disabled='true']:opacity-50",
      className
    )}
    {...props}
  />```
```

**Comment by BelkacemYerfa** [comment]
Hi @lenocin 

Could you provide more informations about the issue that you have with the default style of the `<Command />` component, so we can help to provide you with additional informations.

**Comment by Chaos-19** [comment]
I had the same issue and I solved it using [lenocin](https://github.com/lenocin) solution.

**Comment by parnexcodes** [comment]
Thanks I had the same issue with this component and another one.

**Comment by BelkacemYerfa** [comment]
Hi again!

So about the issue that most people where facing is duo to cmdk version that they're using, and this issue appears with the cmdk@1.0.0 version, and to fix it you have 2 options:
1. Downgrade the version to cmdk@0.2.1
2. Use the fix made by @lenocin here

Thanks again for the report, the issue will be closed now.
