### ISSUE TITLE
Checkbox tree view component

### ISSUE THREAD

**Issue by bryanjtc** [BelkacemYerfa/shadcn-extension#57]
I would like to see an example or a variant of the tree view that allows something like this:
https://codesandbox.io/p/sandbox/dazzling-chatelet-4hw4tk?file=%2Fsrc%2FDemo.tsx

**Comment by BelkacemYerfa** [comment]
Hi @bryanjtc, thanks for you feedback.

Currently all the team is busy with the upcoming release for the next phase of the library. 

We gonna try to take a look for your request about adding the checkbox field with the tree view as a new variant to the tree view component. But you can try to provide a proper solution if you can.
