### ISSUE TITLE
[Communication]: Add discussion tab to the project

### ISSUE THREAD

**Issue by alamenai** [BelkacemYerfa/shadcn-extension#60]
## Description

The addition of a discussion tab to the project aims to enhance communication and collaboration among team members. 

This feature provides a designated space for sharing ideas, asking questions, and providing updates related to the project.

By centralizing communication within the project platform, team members can easily track discussions, contribute insights, and stay informed about the progress of tasks and objectives. 

The discussion tab fosters transparency, encourages active participation, and streamlines communication channels, ultimately leading to more efficient project management and better outcomes.

**Comment by BelkacemYerfa** [comment]
Hi @alamenai thanks for your contribution.

Yes, you're right about this we were planing on opening the discussions section, and seems it is the proper time for it.
