### ISSUE TITLE
[Feature]: Add vertical timeline component

### ISSUE THREAD

**Issue by alamenai** [BelkacemYerfa/shadcn-extension#61]
## Description

This feature request proposes the addition of a vertical timeline component to our project. 

A vertical timeline provides a **chronological display of events** or activities vertically along a single axis, offering users an intuitive way to track the sequence of occurrences.

## Details

- [x] Component Functionality: The vertical timeline component will allow users to visualize events or milestones in a vertical layout.
- [x] Customization Options: Users should be able to customize the appearance of timeline elements, such as event markers, timeline connectors, and labels, to suit their application's design requirements.

- [x] Interactive Features: The component may include interactive features such as click events or tooltips to provide additional information about timeline events.
- [x] Responsive Design: The component should be designed to adapt to various screen sizes and orientations, ensuring a consistent user experience across different devices.

- [x] Accessibility Considerations: Accessibility features such as keyboard navigation and screen reader support should be implemented to ensure inclusivity.

## Use Cases:

- [x] Education: Displaying historical events or milestones in a curriculum.
- [x] Project Management: Tracking project milestones and deadlines.
- [x] Personal Timelines: Visualizing personal achievements or life events.

## Examples

![image](https://github.com/BelkacemYerfa/shadcn-extension/assets/20143684/264d0eef-cb68-40b2-8fe4-31f793c1f1ab)

![image](https://github.com/BelkacemYerfa/shadcn-extension/assets/20143684/395e4da6-17a6-4f7a-b091-27b161154d06)

**Comment by BelkacemYerfa** [comment]
Hi @alamenai, thanks on you contribution.

We were welling to support this timeline component as a part of the library, but actually there is an open [PR](https://github.com/shadcn-ui/ui/pull/3374) for this in shadcn and the feedback that he gots is really positive and it is a solid implementation.

So since this is provided there we are not going to support it.
