### ISSUE TITLE
[Security]: 1 High severity vulnerability found

### ISSUE THREAD

**Issue by alamenai** [BelkacemYerfa/shadcn-extension#62]
## Steps

1. Clone the project.

2. Run `npm install`

3.  Run `npm audit`

## Expected

Safe dependencies

## Current

![image](https://github.com/BelkacemYerfa/shadcn-extension/assets/20143684/4abf426c-b68f-4af5-93f3-37d93242e983)

**Comment by BelkacemYerfa** [comment]
Hi @alamenai thanks for your contribution.

As i see this vulnerability comes from ladash since the version that we have is an old one, so it just need an update.
