### ISSUE TITLE
Highlight delete button on uploaded files when the user hove on file card

### ISSUE THREAD

**Issue by alamenai** [BelkacemYerfa/shadcn-extension#63]
## Description

Enhance the uploaded files by making the delete button on uploaded file cards more visible when a user hovers over the file card. This improves user experience by clearly indicating the delete action.

![a7e65db1-5bee-4f5a-9cb2-87b5c1ccb776](https://github.com/BelkacemYerfa/shadcn-extension/assets/20143684/68326ea9-7700-4c1b-84e4-9aff2c917990)

**Comment by alamenai** [comment]
HI @BelkacemYerfa , any feedback reg this one?

**Comment by BelkacemYerfa** [comment]
Hi @alamenai!

Sorry for this one, i added the task for but i didn't gave you a feedback.

My main idea on this is just to make the stroke of the svg red.
