### ISSUE TITLE
Drag and Drop - How do I add it?

### ISSUE THREAD

**Issue by Imaginativeone** [BelkacemYerfa/shadcn-extension#75]
Please provide some guidance about how I'd add drag and drop. Thanks.

**Comment by BelkacemYerfa** [comment]
Hello @Imaginativeone.

I'm not sure of what you mean by a guide for drag & drop, but if u want a way to add drag & drop to any part of your ui components, i recommend to check dnd-kit [here](https://docs.dndkit.com/), it will suited for all cases, performant and lightweight.

**Comment by Imaginativeone** [comment]
@BelkacemYerfa For now, I might be relegated to this: https://github.com/brimdata/react-arborist In time, I'd like to make something like it by using your technique(s).

**Comment by BelkacemYerfa** [comment]
Hi again @Imaginativeone.

I have looked at [react-arborist](https://github.com/brimdata/react-arborist) that you have mentioned, The approach they use is more abstract that what we use, but if you want to build something similar but having more control over the component, you can check the source code of out [Tree View](https://github.com/BelkacemYerfa/shadcn-extension/blob/master/src/registry/default/extension/tree-view-api.tsx) component, it should provide a solid starting point for you, and also dnd-kit has an example on their repo on how u can build tree like that one using there library, you can check the example code [here](https://github.com/clauderic/dnd-kit/blob/master/stories/3%20-%20Examples/Tree/SortableTree.tsx), the live example deployed on [storybook](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-tree-sortable--all-features). Those should provide a solid starting point for you.

We can help you a beat with some implementation details, this is an invite for our discord account if you want to chat with other contributors about those stuff, and also you can reach us : https://discord.gg/H7AjYkXn.
