### ISSUE TITLE
Multi Selector Item is not selectable 

### ISSUE THREAD

**Issue by codepvn** [BelkacemYerfa/shadcn-extension#76]
I'm unable to select MulticSelector Item and also the items are not added to badge

**Comment by codepvn** [comment]
![Screenshot 2024-07-26 170149](https://github.com/user-attachments/assets/7487d498-4560-4f8c-be8d-b33c46165d89)

**Comment by tsensei** [comment]
@codepvn I am facing the same issue, how did you resolve ?

**Comment by BelkacemYerfa** [comment]
Hello @tsensei @codepvn,

The issue that u're facing is related to the cmdk package, there is 2 ways to fix it:
1. Use the cmdk@0.2.1 and it will work automatically
2. Update the `data-disabled` to data-[disabled=true] CommandItem, as u see here 
![image](https://github.com/user-attachments/assets/6f46b73a-d691-4e68-90e4-b3113b439017)

Thanks for u're feedback.
