### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lalaghoury** [BelkacemYerfa/shadcn-extension#77]
![image](https://github.com/user-attachments/assets/922b2ded-5fd8-41fa-917b-af8e5fd51b16)
when i select the text then it turns to black

**Comment by BelkacemYerfa** [comment]
Hi @lalaghoury, thanks for your feedback !

It seems that the issue is with the select highlighting with dark mode.

Could you provide more informations about the web browser that you're using, so we can reproduce the issue so we can fix it?

Thanks again.
